{{- range .Values.ingress.hosts }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .tls.name }}
  namespace: {{ $.Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .tls.cert }}
  tls.key: {{ .tls.key }}
{{- end }}