apiVersion: v1
kind: Service
metadata:
  name: {{ include "crafty.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: crafty
      port: {{ .Values.service.ports.crafty.port }}
      targetPort: {{ .Values.service.ports.crafty.targetPort }}
    - name: dynmap
      port: {{ .Values.service.ports.dynmap.port }}
      targetPort: {{ .Values.service.ports.dynmap.targetPort }}
  selector:
    app: {{ include "crafty.name" . }}